name: Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: List test DLLs
      run: ls -la GenericEFCoreHelper.Tests/bin/Debug/net9.0/

    - name: Run tests
      run: dotnet test GenericEFCoreHelper.Tests/GenericEFCoreHelper.Tests.csproj --no-build --verbosity normal

    - name: Pack
      if: success()
      run: dotnet pack --configuration Release --no-build

    - name: Publish to NuGet
      if: success()
      env:
        NUGET_API_KEY: ${{ secrets.GENERICEFCOREHELPER_APIKEY }}
      run: dotnet nuget push bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
